"""add tickers 

Revision ID: 45abd19a0689
Revises: e5876da1c367
Create Date: 2022-09-07 23:47:37.882289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45abd19a0689'
down_revision = 'e5876da1c367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('stock', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stock_move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('buy_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stock_move')
    op.drop_table('ticker')
    # ### end Alembic commands ###
